const boosters = [
  {
    id: 0,
    title: "Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/1.png"),
  },
  {
    id: 1,
    title: "Stone Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/2.png"),
  },
  {
    id: 2,
    title: "Gas Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/3.png"),
  },
  {
    id: 3,
    title: "Neon Fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/4.png"),
  },
  {
    id: 4,
    title: "Neon Multy-fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/5.png"),
  },
  {
    id: 5,
    title: "Neon Multy-fireplace",
    text: "Better Fireplace boosts mining speed",
    description: "Increase passive mining speed",
    icon: require("../../assets/hot/fire/5.png"),
  },

  {
    id: 10,
    title: "Basic Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/1.png"),
    mission_text: "",
  },
  {
    id: 11,
    title: "Neon Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/2.png"),
    mission_text: "Join village",
  },
  {
    id: 12,
    title: "Titanium Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/3.png"),
    mission_text: "Download the mobile app and import your account",
  },
  {
    id: 13,
    title: "Jedi Wood",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/4.png"),
    mission_text: "Deposit 1 NEAR on your account",
  },
  {
    id: 14,
    title: "Uranium Boxes",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/5.png"),
    mission_text: "Deposit 1 USDT on your account",
  },
  {
    id: 15,
    title: "Uranium Boxes",
    text: "Better wood give you a multiplier to HOT mining. Mining speed is Wood × Fireplace",
    description: "Boost mining speed by\n1.5x.. 2x.. 3x times!",
    icon: require("../../assets/hot/wood/5.png"),
    mission_text: "Deposit NFT on your account",
  },

  {
    id: 20,
    title: "Wooden Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/1.png"),
  },
  {
    id: 21,
    title: "Metal Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/2.png"),
  },
  {
    id: 22,
    title: "Modular Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/3.png"),
  },
  {
    id: 23,
    title: "Liquid Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/4.png"),
  },
  {
    id: 24,
    title: "Titanium Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/5.png"),
  },
  {
    id: 25,
    title: "Titanium Storage",
    text: "Better storage holds more HOT and you can claim it less often",
    description: "Increase the fill\ntime to claim less often",
    icon: require("../../assets/hot/storage/5.png"),
  },
];
